name: numberlink
channels:
  - https://prefix.dev/conda-forge
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10
  - pip
  - pip:
      - -e .
      - numpy>=1.21, <3
      - gymnasium>=1.1, <2
