name: numberlink
channels:
  - https://prefix.dev/conda-forge
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10
  - pip
  - pip:
      - -e .
      - numpy>=2.0, <3
      - gymnasium>=1.0, <2
      - pygame>=2.0, <3
