name: numberlink-dev
channels:
  - https://prefix.dev/conda-forge
  - conda-forge
  - nodefaults
dependencies:
  - shellcheck *
  - yamllint *
  - python >=3.10
  - furo *
  - sphinx-copybutton *
  - sphinx-autodoc2 *
  - sphinx-sitemap *
  - myst-parser *
  - linkify-it-py *
  - pip
  - pip:
      - ruff
      - -e .
      - numpy>=1.21, <3
      - gymnasium>=1.1, <2
      - pygame-ce>=2.1.3, <3
      - pyright
      - mypy
      - pyrefly
      - ty
      - ipykernel
      - ipywidgets
      - ipyevents
      - pre-commit
      - cffconvert
      - imageio
      - types-defusedxml
      - types-pytz
      - types-pycurl
      - ipython
      - pillow
      - pytest
      - nose2
      - pytest-cov
      - tox
      - hatch
