[build-system]
requires = ["hatchling>=1.27.0,<2"]
build-backend = "hatchling.build"

[project]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Free Threading :: 3 - Stable",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed",
]
name = "numberlink"
dynamic = ["version"]
description = "NumberLink puzzle environment for Gymnasium"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Misagh Soltani", email = "misaghsoltani@gmail.com" }]
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = [
    "NumberLink",
    "Puzzle",
    "Game",
    "Gymnasium",
    "OpenAI Gym",
    "gym",
    "AI",
    "reinforcement learning",
    "deep reinforcement learning",
    "search",
    "heuristic search",
    "pathfinding",
    "planning",
]
dependencies = ["numpy>=1.21,<3", "gymnasium>=1.1,<2"]

[project.optional-dependencies]
human = ["pygame-ce>=2.1.3,<3"]
notebook = [
    "ipython>=8.0,<10",
    "ipywidgets>=7.7,<9",
    "ipyevents>=2.0,<3",
    "Pillow>=9.0,<13",
]

# run-numberlink will run the CLI
[project.urls]
GitHub = "https://github.com/misaghsoltani/NumberLink/"
Documentation = "https://misaghsoltani.github.io/NumberLink/"


[project.scripts]
numberlink = "numberlink.main:main"
numberlink-cli = "numberlink.cli:main"

[project.entry-points."gymnasium.envs"]
NumberLinkRGB-v0 = "numberlink.registration:env_creator"
NumberLinkRGBVector-v0 = "numberlink.registration:vector_env_creator"

# [tool.hatchling.packages.find]
# include = ["numberlink*"] # Only consider package names starting with numberlink (e.g. numberlink, numberlink.submodule, etc.) when auto-discovering packages
# namespaces = false # Don't treat directories without an __init__.py as namespace packages, only folders with __init__.py count

[tool.hatchling]
include-package-data = true

# [tool.hatch.metadata]
# allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["numberlink"]
include = [
    # "numberlink/**",
    "numberlink/py.typed",
    "numberlink/assets/**",
    "README.md",
]
exclude = ["*.py[cod]", "__pycache__/**", ".DS_Store", ".git", ".vscode"]

[tool.hatch.build.targets.sdist]
packages = ["numberlink"]
include = [
    # "numberlink/**",
    "numberlink/py.typed",
    "numberlink/assets/**",
    "README.md",
]
exclude = [
    "*.py[cod]",
    "__pycache__/**",
    ".DS_Store",
    ".vscode",
    ".git",
    ".pixi",
]

[tool.hatch.version]
path = "numberlink/__init__.py"

[dependency-groups]
doc = [
    "furo>=2024.1.29,<2027",
    "sphinx-copybutton>=0.5.2,<1",
    "sphinx-autodoc2>=0.5.0,<1",
    "sphinx-sitemap>=2.6.0,<3",
    "myst-parser[linkify]>=3.0.0,<6",
]
default = ["numberlink"]
human = [{ include-group = "default" }, "pygame-ce>=2.1.3,<3"]
notebook = [
    { include-group = "default" },
    "ipython>=8.0,<10",
    "ipywidgets>=7.7,<9",
    "ipyevents>=2.0,<3",
    "Pillow>=9.0,<13",
]
dev = [
    { include-group = "default" },
    { include-group = "human" },
    { include-group = "notebook" },
    { include-group = "doc" },
    { include-group = "test" },
    { include-group = "build" },
    "ruff>=0.14.1,<1",
    "pyright>=1.1.400,<2",
    "mypy>=1.16,<3",
    "pyrefly>=1.0.0,<2",
    "ty>=0.0.1,<1",
    "shellcheck-py>=0.10.0,<1",
    "yamllint>=1.35.0,<2",
    "pre-commit>=3.7.0,<5",
    "cffconvert>=2.0.0,<3",
    "types-defusedxml>=0.7.0,<1",
    "types-pytz>=2024.1.0,<2027",
    "types-pycurl>=7.45.0,<8",
    "imageio>=2.34.0,<3",
]
test = [
    { include-group = "default" },
    { include-group = "human" },
    { include-group = "notebook" },
    { include-group = "doc" },
    "pytest>=8.0,<10",
    "nose2>=0.14.0,<1",
    "pytest-cov>=5.0,<8",
    "tox>=4.15,<5",
]
build = [
    { include-group = "default" },
    { include-group = "human" },
    { include-group = "notebook" },
    "hatch>=1.12.0,<2",
]
all = [
    { include-group = "default" },
    { include-group = "dev" },
    { include-group = "build" },
    { include-group = "doc" },
    { include-group = "test" },
    { include-group = "human" },
    { include-group = "notebook" },
]
